PJ2	:main.o util.o heap.o
	g++ -o PJ2 main.o util.o

main.o	:main.cpp util.h heap.h
	g++ -c -Wall main.cpp

util.o	:util.cpp util.h
	g++ -c -Wall util.cpp 
heap.o	:heap.cpp heap.h
	g++ -c -Wall heap.cpp
