PJ1	:main.o IS.o QS.o MS.o
	g++ -o PJ1 main.o IS.o QS.o MS.o

main.o	:main.cpp IS.h QS.h MS.h
	g++ -c -Wall main.cpp

IS.o	:IS.cpp IS.h
	g++ -c -Wall IS.cpp

QS.o	:QS.cpp QS.h
	g++ -c -Wall QS.cpp

MS.o	:MS.cpp MS.h
	g++ -c -Wall MS.cpp
